# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba524717b8b9663a3c79078a9b7ecbc882ab5087054760825cfd610fd0daf264654ff552fc7e1b675f04a0bf2d40fb2a0047d281033cccdf75ecc2bd7228a798

test:
  secret_key_base: 343e5546e5631dd9e925fc63c85927d4e934e357878c9545040f0eac9c8d2f26077837a009b0c8584430aaf254084956c2dd6dba7aff89b00415c78ab494b816

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
